Add assertFieldIsRequired tests to Content types and Paragraph types
Gizra/drupal-starter pull request #327
Opened 2022-09-30 11:12 UTC by dipakmdhrm

#289 

- Add `assertFieldIsRequired` & 'assertFieldIsNotRequired' tests to Content types and Paragraph types.

2022-09-30 12:56 UTC, mariano-dagostino requested changes

2022-09-30 12:56 UTC, mariano-dagostino commented on web/modules/custom/server_general/tests/src/ExistingSite/ServerGeneralEntityTypeTestBase.php
> +  const OPTIONAL_FIELDS = [];
I think we could either, document the types of each const here.. Or maybe better define an Interface with four methods and they respective return types.

Something like

```
interface RequiredAndOptionalFieldTestInterface {

  /**
   *  The entity type to assert it exists.
   *
   * @return string
   *   An entity type name.
   */
  public function entityType() : string;

  ...

}

So the compiler will let us know there is something off in new tests.

2022-09-30 15:59 UTC, dipakmdhrm commented on web/modules/custom/server_general/tests/src/ExistingSite/ServerGeneralEntityTypeTestBase.php
> +  const OPTIONAL_FIELDS = [];
That's a great suggestion. Thank you!
It's done.

2022-09-30 16:01 UTC, dipakmdhrm commented
### Update: 

- Added RequiredAndOptionalFieldTestInterface interface

**TB:1.9/2h**

2022-09-30 18:15 UTC, mariano-dagostino reviewed
@dipakmdhrm Two more changes and MWG.

2022-09-30 18:15 UTC, mariano-dagostino commented on web/modules/custom/server_general/tests/src/ExistingSite/RequiredAndOptionalFieldTestInterface.php
> +   * @return array
@dipakmdhrm would be great to use `[]string` here. I think phpstan can detect this as well.

2022-09-30 18:15 UTC, mariano-dagostino commented on web/modules/custom/server_general/tests/src/ExistingSite/RequiredAndOptionalFieldTestInterface.php
> +   * @return array
Same here

2022-09-30 21:12 UTC, merged

2022-10-04 10:38 UTC, bboro commented on web/modules/custom/server_general/tests/src/ExistingSite/ServerGeneralContentTypeNews.php
> +class ServerGeneralContentTypeNews extends ServerGeneralContentTypeTestBase {
Test classes need to end with "Test" otherwise they don't run: https://app.travis-ci.com/github/Gizra/drupal-starter/jobs/584404313 look for `ServerGeneralContentTypeNews` it's not listed in the list of tests ran