Added alignment and credit field to MediaCaptionTrait
Gizra/drupal-starter pull request #442
Opened 2023-03-01 18:28 UTC by balagan73

MediaCaptionTrait now can display the credit field and can handle alignment.
Credits to @dipakmdhrm

2023-03-01 19:13 UTC, amitaibu requested changes
Thanks. Screenshots would be nice :)

In any case, I think we should change strategy, and move to composing the elements together

2023-03-01 19:13 UTC, amitaibu commented on web/modules/custom/server_general/src/MediaCaptionTrait.php
> +      '#credit' => $credit,
I think we should change this to $items - that will get a render array. So we can pass caption, credit, etc'.

Then we could use the `verticalSpacing` -- we can pass alignment there.

2023-03-01 21:52 UTC, balagan73 commented on web/modules/custom/server_general/src/MediaCaptionTrait.php
> +      '#credit' => $credit,
![image](https://user-images.githubusercontent.com/3536805/222272859-4bdf9439-1ae5-46b0-8ea8-c2ac4734b96f.png)

verticalSpacingTiny has gap-y-2 class, and here we have 8px gap. Should we create another vertical spacer with gap-y-1 class?

2023-03-02 05:26 UTC, amitaibu commented on web/modules/custom/server_general/src/MediaCaptionTrait.php
> +      '#credit' => $credit,
Let's use `verticalSpacingTiny` as is

2023-03-02 05:26 UTC, amitaibu commented on web/themes/custom/server_theme/server_theme.theme
> +      'credit' => NULL,
=> `$items => []`

2023-03-02 07:47 UTC, balagan73 commented
Then we can probably get rid of the templates for the caption, video and media.

2023-03-02 07:56 UTC, balagan73 commented
Style guide after the updates.

![image](https://user-images.githubusercontent.com/3536805/222366367-9609adc9-1edb-4620-bc37-03a85f1984f5.png)

2023-03-02 08:36 UTC, balagan73 commented
Maybe deleting the video and image templates is not a good idea. Added wrappers for caption font colors.

2023-03-02 09:25 UTC, amitaibu commented on web/themes/custom/server_theme/server_theme.theme
> +      'credit' => NULL,
^^. We should remove caption and credit, and call it `$items`

2023-03-02 09:26 UTC, amitaibu commented on web/modules/custom/server_style_guide/src/Controller/StyleGuideController.php
>      return [
We shouldn't be calling these theme functions form StyleGuide - we should call the method on the trait. You can mock the $entity for that

2023-03-02 09:47 UTC, balagan73 commented
I will start again in a new branch, this went in a wrong way.

2023-03-02 09:47 UTC, closed without merging