Add Documents list element
Gizra/drupal-starter pull request #445
Opened 2023-03-06 21:44 UTC by amitaibu

- Add Documents list paragraph
- wrapContainerWide, now accepts an optional background color. If no color then a transparent background is added and no `py` is added, so `verticalSpacing` behaves normally.
- Added `buildElementItemsWithViewMore` as a generic way of adding items that can be hidden with "View more" button
- Button is now using `<button>` tag instead of `<a>`

| Style guide | Node view | Node view after "View more" | Node edit |
| -- | -- | -- | -- |
| ![image](https://user-images.githubusercontent.com/125707/223236166-e3f4277c-d56b-471c-9f83-87802399109e.png) | ![image](https://user-images.githubusercontent.com/125707/223239288-bc4d93a7-8f03-4486-826a-08d45bc0e77c.png) | ![image](https://user-images.githubusercontent.com/125707/223239530-f6f45c36-c85c-46dc-a052-0dbefa74f9f6.png) |![image](https://user-images.githubusercontent.com/125707/223239852-9cc71f83-6d28-48b6-a379-6f9cb6c9c6da.png) |

2023-03-07 19:37 UTC, amitaibu commented
- Added tests.
- Added to migration.

![image](https://user-images.githubusercontent.com/125707/223533786-a5fbb0f2-0936-4487-8452-8597539f8ed5.png)

2023-03-08 19:32 UTC, mariano-dagostino requested changes
@amitaibu Looks good. I finished my review with a few improvements.

2023-03-08 19:38 UTC, amitaibu commented on web/modules/custom/server_general/src/ElementTrait.php
> +    $elements[] = $this->buildElementItemsWithViewMore($documents, $button, 2);
I could also remove the view more text, and always use that. My concern was if we'd like to show different kind of button (e.g. primary Vs secondary). But let's be lazy - I'll "hardcode" the button.

Extending projects can change it if needed.

2023-03-08 19:39 UTC, amitaibu commented on web/modules/custom/server_general/src/Plugin/EntityViewBuilder/MediaDocument.php
> +    $file = $this->getReferencedEntityFromField($entity, 'field_media_file');
I don't think it's needed, PEVB is just reaching to the Media's field.

2023-03-08 19:41 UTC, amitaibu commented on web/modules/custom/server_style_guide/src/Controller/StyleGuideController.php
> +        'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGsAAAB7CAMAAABEt46lAAAACXBIWXMAAA7zAAAO8wEcU5k6AAAAEXRFWHRUaXRsZQBQREYgQ3JlYXRvckFevCgAAAATdEVYdEF1dGhvcgBQREYgVG9vbHMgQUcbz3cwAAAALXpUWHREZXNj
Ok, if that's the reaction - I could load an existing Media image :angel:

2023-03-08 19:53 UTC, amitaibu commented
Addressed comments, thanks.

| Node View | Style guide |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/125707/223831089-fcbe0223-207f-4ad1-a085-481900881cc2.png) | ![image](https://user-images.githubusercontent.com/125707/223831196-d8d8dff8-b598-45ed-be07-0ca514e732f4.png)|

2023-03-09 04:56 UTC, amitaibu commented on web/modules/custom/server_style_guide/src/Controller/StyleGuideController.php
> +    $file = $file_storage->load($fid);
@mariano-dagostino I think maybe to revert to that scary data URI -- so style guide won't depend on actual content. (Think of this as a `View.elm` -- it shouldn't perform any DB query)

Agree?

2023-03-09 16:44 UTC, amitaibu commented on web/modules/custom/server_style_guide/src/Controller/StyleGuideController.php
> +    $file = $file_storage->load($fid);
https://github.com/Gizra/drupal-starter/pull/445/commits/cc84d21cfefbbaf0a95bbc30c9c6de7b25bae6df

2023-03-09 17:04 UTC, mariano-dagostino commented on web/modules/custom/server_style_guide/src/Controller/StyleGuideController.php
> +        'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGsAAAB7CAMAAABEt46lAAAACXBIWXMAAA7zAAAO8wEcU5k6AAAAEXRFWHRUaXRsZQBQREYgQ3JlYXRvckFevCgAAAATdEVYdEF1dGhvcgBQREYgVG9vbHMgQUcbz3cwAAAALXpUWHREZXNj
```suggestion
        Url::fromUserInput('/modules/custom/server_migrate/files/drupal-starter.pdf')->toString(),
```

2023-03-09 17:04 UTC, mariano-dagostino commented on web/modules/custom/server_style_guide/src/Controller/StyleGuideController.php
> +        'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGsAAAB7CAMAAABEt46lAAAACXBIWXMAAA7zAAAO8wEcU5k6AAAAEXRFWHRUaXRsZQBQREYgQ3JlYXRvckFevCgAAAATdEVYdEF1dGhvcgBQREYgVG9vbHMgQUcbz3cwAAAALXpUWHREZXNj
@amitaibu :point_up:

2023-03-09 17:06 UTC, amitaibu commented on web/modules/custom/server_style_guide/src/Controller/StyleGuideController.php
> +        'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGsAAAB7CAMAAABEt46lAAAACXBIWXMAAA7zAAAO8wEcU5k6AAAAEXRFWHRUaXRsZQBQREYgQ3JlYXRvckFevCgAAAATdEVYdEF1dGhvcgBQREYgVG9vbHMgQUcbz3cwAAAALXpUWHREZXNj
Much nicer!

2023-03-09 17:39 UTC, mariano-dagostino approved these changes

2023-03-09 17:40 UTC, merged