Text styles (prose and non-prose) on Style guide page
Gizra/drupal-starter pull request #488
Opened 2023-04-13 10:49 UTC by amitaibu

| Non prose | Prose |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/125707/231736590-d6720bf4-f2f4-430c-9ad5-30aa6574a141.png) | ![image](https://user-images.githubusercontent.com/125707/231736613-b8c7ec6b-c219-44ac-9bd8-66c190e6f44b.png) |

2023-04-13 10:50 UTC, amitaibu commented on web/modules/custom/server_style_guide/src/Controller/StyleGuideController.php
> +    // Font weight for a string.
```suggestion
```

2023-04-13 18:38 UTC, mariano-dagostino requested changes
Do we want to standardize the sizes of headers for both options?

![Screenshot_2023-04-13_15-35-10](https://user-images.githubusercontent.com/5313631/231852540-309f0a09-e229-4e28-a955-199dffa6cff9.png)

2023-04-14 08:59 UTC, amitaibu commented
@isapisa @nora-novak What do you think about Mariano's comment - should the H1-H5 be the same in prose and non prose?

2023-04-21 08:58 UTC, amitaibu commented
We are now showing the same font size for headings (h1- h5) on prose and non-prose, as we wrap all of them with `wrapProseText`.

The non-prose version should not have a margin applied to it - and that's the case.

![image](https://user-images.githubusercontent.com/125707/233592339-83ab77b3-8ed9-4bc8-b769-8038c017d873.png)

2023-04-21 14:07 UTC, mariano-dagostino approved these changes

2023-04-21 14:11 UTC, amitaibu commented on web/modules/custom/server_style_guide/templates/server-style-guide-text-styles.html.twig
> +<h5>This is an example for H5</h5>
```suggestion
<h1>This is an example for h1</h1>
<h2>This is an example for h2</h2>
<h3>This is an example for h3</h3>
<h4>This is an example for h4</h4>
<h5>This is an example for h5</h5>
```

2023-04-21 15:03 UTC, merged