Add anchor links to all headings
Gizra/drupal-starter pull request #492
Opened 2023-04-14 10:13 UTC by amitaibu

![image](https://user-images.githubusercontent.com/125707/232017041-98938d5a-ae30-45a1-9078-d06d2c6a0e26.png)

2023-04-14 10:59 UTC, amitaibu commented
@isapisa @nora-novak What do you think?

2023-04-14 13:39 UTC, isapisa commented
@amitaibu why would we want to do this?

2023-04-14 14:43 UTC, amitaibu commented
This allows adding anchors to any h2 - h6 heading. Useful on long pages/ posts. Thanks to this we can for example link to this section https://www.gizra.com/jobs/candidates-info/#timebox

2023-04-20 09:39 UTC, mariano-dagostino requested changes
@amitaibu Do we want to wrap this in an 'once()' call?

2023-04-20 10:23 UTC, amitaibu commented on web/themes/custom/server_theme/server_theme.libraries.yml
> +    - core/jquery.once
I'm not sure if this is needed, I'll check

2023-04-20 10:23 UTC, amitaibu commented on web/themes/custom/server_theme/src/js/scripts.js
> +      // Add anchor links to all headings.
@mariano-dagostino Good call about `once`. I think it might not be needed since AnchorJs already does it [here](https://github.com/bryanbraun/anchorjs/blob/7820d5f6a6d41eb92000ab9c22b9362262a6b8a8/anchor.js#L260-L265)

2023-04-20 14:32 UTC, mariano-dagostino requested changes
@amitaibu Finished my review.

2023-04-20 14:32 UTC, mariano-dagostino commented on web/themes/custom/server_theme/server_theme.libraries.yml
> +    - core/drupal
Is this even required? The anchor.js seems a standalone script.

2023-04-20 14:32 UTC, mariano-dagostino commented on web/themes/custom/server_theme/server_theme.libraries.yml
> +    /libraries/anchor-js/anchor.js: {}
This is not a minimized version. I wonder if makes sense to move to the theme and point to `/dist` instead.

2023-04-20 16:47 UTC, amitaibu commented on web/themes/custom/server_theme/server_theme.libraries.yml
> +    /libraries/anchor-js/anchor.js: {}
Done, changed to the minified file

2023-04-20 16:56 UTC, amitaibu commented
Re-rolled PR

2023-04-21 13:51 UTC, mariano-dagostino reviewed
@amitaibu This looks good and the functionality seems to work ok locally. However https://www.bryanbraun.com/anchorjs/#dont-run-it-too-late mentioned something interesting, maybe the link is not there yet in a heavy based JS site. I think we need to play with the JS weight to load it as early as possible.

2023-05-03 09:37 UTC, amitaibu commented
> maybe the link is not there yet in a heavy based JS site

As I can't see the problem, let's get it in, and deal once we have a real use case.

2023-05-05 18:05 UTC, mariano-dagostino commented
@amitaibu I removed the custom font call as it will interfere with #280 also, there is one character that breaks the ids generation. 6721707

Finally some examples of how to use tailwind classes.

https://user-images.githubusercontent.com/5313631/236534218-4e8965c0-134f-4fad-a7fc-c68507292b57.mp4

2023-05-05 18:05 UTC, mariano-dagostino approved these changes

2023-05-07 09:15 UTC, amitaibu commented
Made the icon slightly bigger

![image](https://user-images.githubusercontent.com/125707/236668759-39a9dabd-57ba-46e6-aabd-ee919d798a1f.png)

2023-05-07 10:56 UTC, merged