Freetext search assertion
Gizra/drupal-starter pull request #496
Opened 2023-04-19 11:53 UTC by AronNovak

Protect from accidental PHP-based stemming / trimming

2023-04-19 11:54 UTC, AronNovak commented on web/modules/custom/server_general/tests/src/ExistingSite/ServerGeneralSearchTest.php
> +    // Create an English node.
```suggestion
```

2023-04-19 12:35 UTC, mariano-dagostino requested changes

2023-04-19 12:35 UTC, mariano-dagostino commented on web/modules/custom/server_general/tests/src/ExistingSite/ServerGeneralSearchTest.php
> +    $english_node_title = 'Support to National Development Priorities';
```suggestion
    $english_node_title = 'This is a test';
```

2023-04-20 09:14 UTC, mariano-dagostino approved these changes

2023-04-20 09:14 UTC, merged