Issue-693: Disallow scheduler on locked pages (if scheduler module is enabled)
Gizra/drupal-starter pull request #754
Opened 2024-11-14 07:36 UTC by sonvir249

Clsoes #693

2024-11-14 09:44 UTC, mgurjanov requested changes
Overall nice attempt at this issue! I left some change requests, though.

2024-11-14 09:44 UTC, mgurjanov commented on web/modules/custom/server_general/server_general.module
> +  if ($entity->getEntityType()->id() !== 'node') {
I think we implemented this locked pages only for `Landing page` bundle, so we could maybe narrow down this check to `$entity->bundle() !== 'landing_page'` not to trigger this for every node.

2024-11-14 09:44 UTC, mgurjanov commented on web/modules/custom/server_general/server_general.module
> +  $allowed = TRUE;
We shouldn't set $allowed = TRUE by default as other modules could also call this hook. Instead I would just return FALSE where our locked page conditions are met and otherwise just return leaving our hook neutral.

2024-11-14 09:44 UTC, mgurjanov commented on web/sites/default/default.services.yml
> +  security.enable_super_user: true
This has no connection to this PR.

2024-11-14 09:44 UTC, mgurjanov commented on web/modules/custom/server_general/server_general.module
> +      $form['scheduler_settings']['#description'] = t('This is the help text for the details section.');
This text could explain why these options are read only.

2024-11-14 12:22 UTC, sonvir249 commented on web/modules/custom/server_general/server_general.module
> +  if ($entity->getEntityType()->id() !== 'node') {
@mgurjanov this is done.

2024-11-14 12:22 UTC, sonvir249 commented on web/modules/custom/server_general/server_general.module
> +  $allowed = TRUE;
@mgurjanov this is done.

2024-11-14 12:22 UTC, sonvir249 commented on web/sites/default/default.services.yml
> +  security.enable_super_user: true
@mgurjanov removed this file.

2024-11-14 12:24 UTC, sonvir249 commented on web/modules/custom/server_general/server_general.module
> +      $form['scheduler_settings']['#description'] = t('This is the help text for the details section.');
Displaying the description as an error meesage. Please do let me know if any changes needed. Thanks!
![image](https://github.com/user-attachments/assets/fe262eff-b65b-485d-b006-8d0b240cb5d4)

2024-11-14 12:30 UTC, mgurjanov approved these changes
Looks good to me. Just one small typo fix.

2024-11-14 12:30 UTC, mgurjanov commented on web/modules/custom/server_general/server_general.module
> +          'message' => t('This page is locked hence the publish and unpublish dates can not be changed. Also schedling dates won\'t work.'),
```suggestion
          'message' => t('This page is locked hence the publish and unpublish dates can not be changed. Also scheduling dates won\'t work.'),
```

2024-11-14 12:32 UTC, sonvir249 commented
@amitaibu @mgurjanov Just a suggestion, shouldn't we add github actions to catch  the drupal php and twig code stanrdard, theme build issues whenever any PR is rasied or commit is pushed.

2024-11-14 12:34 UTC, mgurjanov commented
@sonvir249 We do run `ddev phpcs` or `ddev phpstan` locally prior to pushing code to github.

2024-11-14 12:37 UTC, sonvir249 commented on web/modules/custom/server_general/server_general.module
> +          'message' => t('This page is locked hence the publish and unpublish dates can not be changed. Also schedling dates won\'t work.'),
@mgurjanov fixed the spelling mistake.

2024-11-14 12:39 UTC, sonvir249 commented
> @sonvir249 We do run `ddev phpcs` or `ddev phpstan` locally prior to pushing code to github.

I also do that on local, but having it in the pipeline adds an extra layer of assurance to ensure nothing goes wrong with the code.

2024-11-14 12:50 UTC, amitaibu commented on web/modules/custom/server_general/server_general.module
> +  $module_handler = \Drupal::service('module_handler');
Let's move this to a helper function.
Also, let's use the style if return early. So

```
$module_handler = \Drupal::service('module_handler');
if (!$module_handler->moduleExists('scheduler')) {
  // Scheduler module not enabled.
  return;
}

2024-11-14 12:51 UTC, amitaibu commented on web/modules/custom/server_general/server_general.module
> +    $current_time = time();
https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Datetime%21TimeInterface.php/function/TimeInterface%3A%3AgetCurrentTime/9#:~:text=Returns%20the%20current%20system%20time,time%20the%20method%20was%20called.&text=%24request_time%20%3D%20%5CDrupal%3A%3Atime()%2D%3EgetCurrentTime()%3B

2024-11-14 12:51 UTC, mgurjanov commented
@amitaibu I was thinking of asking for test case, but wouldn't that require installing and enabling scheduler?

2024-11-14 12:52 UTC, amitaibu commented on web/modules/custom/server_general/server_general.module
> +      $form['scheduler_settings']['#description'] = [
Please share a screenshot. Do we have something similar on Drupal-starter?

2024-11-14 12:52 UTC, amitaibu commented on web/modules/custom/server_general/server_general.module
> +  /** @var \Drupal\node\NodeInterface $entity */
I don't think the entity is always `NodeInterface`. In fact, we already have type hinting above `EntityInterface $entity`

2024-11-14 12:55 UTC, amitaibu commented
> I was thinking of asking for test case,

@sonvir249 always go with that gut feeling 😄 

> but wouldn't that require installing and enabling scheduler?

We can have it installed with composer, and the test would enable it. In the future, we could decide to also enable it by default - depends if we see more real world cases where clients need it.

2024-11-14 12:59 UTC, mgurjanov commented
@amitaibu It's funny how it always fires back to me when I don't, and I do follow gut feeling most of the time. Thanks for the reminder!

2024-11-14 13:10 UTC, amitaibu commented
😆 👌

2024-11-14 15:33 UTC, sonvir249 commented on web/modules/custom/server_general/server_general.module
> +  $module_handler = \Drupal::service('module_handler');
@amitaibu This is done.

2024-11-14 15:33 UTC, sonvir249 commented on web/modules/custom/server_general/server_general.module
> +    $current_time = time();
@amitaibu this is done.

2024-11-14 15:42 UTC, sonvir249 commented on web/modules/custom/server_general/server_general.module
> +  /** @var \Drupal\node\NodeInterface $entity */
@amitaibu this is done.

2024-11-14 15:59 UTC, sonvir249 commented
> > ddev phpcs or ddev phpstan
> 
> They are already part of the [Travis](https://github.com/Gizra/drupal-starter/blob/026a54717eb699f8c47d2034940a65da1dd24746/.travis.yml) CI pipieline
> 
> @sonvir249 could you also add a test case please?

@amitaibu Sure, I can handle that. Could you help clarify what areas I should cover in the tests? Also, I don’t have much experience writing test cases, so any references or guidance would be really helpful. Thanks!

2024-11-18 13:06 UTC, amitaibu commented
You can confirm, for example, that the form changes have kicked in.

You can see an existing test [here](https://github.com/Gizra/drupal-starter/blob/09fd86c18565367a819ecea5aa3a5aa4ddb7af70/web/modules/custom/server_general/tests/src/ExistingSite/ServerGeneralNodeLandingPageTest.php)

2024-12-07 18:17 UTC, sonvir249 commented
> You can confirm, for example, that the form changes have kicked in.
> 
> You can see an existing test [here](https://github.com/Gizra/drupal-starter/blob/09fd86c18565367a819ecea5aa3a5aa4ddb7af70/web/modules/custom/server_general/tests/src/ExistingSite/ServerGeneralNodeLandingPageTest.php)

@amitaibu I have added the basic unit test to verify the scheduler form fields on locked and non-locked node forms.

2024-12-08 14:36 UTC, sonvir249 commented
@amitaibu @mgurjanov I faced https://www.drupal.org/project/config_pages/issues/3474241 deprecation notice while removing configured node. Should we apply this patch for `config_pages` module?

2024-12-08 16:23 UTC, amitaibu commented on config/sync/core.extension.yml
> +  scheduler: 0
As this is not a very common feature, I don't think we should enable this by default. It's fine that we download `scheduler`, but we should enable it only from the test.

2024-12-09 04:13 UTC, sonvir249 commented on config/sync/core.extension.yml
> +  scheduler: 0
@amitaibu this is done. Enabling and configuring `scheduler` module from the test.

2024-12-09 14:03 UTC, amitaibu commented on web/sites/default/default.services.yml
> +  security.enable_super_user: true
This shouldn't be changed

2024-12-09 14:05 UTC, amitaibu commented on web/modules/custom/server_general/server_general.module
> +  }
```suggestion
  return !$locked_pages_service->isNodeLocked($entity)
```

2024-12-09 14:05 UTC, amitaibu commented on web/modules/custom/server_general/src/LockedPages.php
> +  /**
Changes on this file can be removed

2024-12-09 16:18 UTC, sonvir249 commented on web/modules/custom/server_general/src/LockedPages.php
> +  public function isModuleEnabled(string $module_name): bool {
@amitaibu this is done.

2024-12-09 16:18 UTC, sonvir249 commented on web/modules/custom/server_general/src/LockedPages.php
> +  /**
@amitaibu this is done.

2024-12-09 16:41 UTC, amitaibu commented on web/modules/custom/server_general/server_general.module
> +      ],
Let's create a twig, and move it there, so we don't end up with css classes inside PHP.

We can have a `wrapDanger` function, like our other [wrappers](https://github.com/Gizra/drupal-starter/blob/73d4d58d45dfb3a21f4235b615640f8e560b2944/web/modules/custom/server_general/src/ElementWrapTrait.php)

2024-12-10 07:54 UTC, sonvir249 commented on web/modules/custom/server_general/server_general.module
> +      ],
@amitaibu Since we are modifying the node edit form, which utilizes the admin theme, any changes made in the `server_theme` theme will not apply to the admin theme.

2024-12-10 11:45 UTC, amitaibu commented on web/modules/custom/server_general/server_general.module
> +      ],
Right, thanks

2024-12-10 11:46 UTC, amitaibu approved these changes
Thanks 🙏

2024-12-10 11:46 UTC, merged